spring:
  application.name: Teacherevaluation_2_0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: znoyhx
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.stu.entity
  configuration:
    map-underscore-to-camel-case: true

app:
  jwt:
    # ??jwt??????????
#    user-secret-key: itcast
    # ??jwt????
    user-secret-key: 7Z8x9y0A1s2D3f4G5h6J7k8L9z0X1c2V3b4N5m6P7q8R9t0Y1U2I3O4P5

    user-ttl: 7200000000
    # ?????????????
    user-token-name: token

deepseek:
  api-url: https://api.deepseek.com/v1/chat/completions
  token: sk-25c5af9fa0f740c3aaa3090bab0da72a
  prompt-prefix: "你是一个教育评价助手，帮我总结这段老师评价内容, 你应该以'该老师'开头,期间应该向我介绍该老师的个人信息, 禁止一切客套话, 只准结合我提供的老师信息和客观评价来总结该老师的评价："
